def on_button_pressed_a():
    piano.note(midi.frequency_to_key(330), music.beat(BeatFraction.WHOLE))
    piano.note(midi.frequency_to_key(349), music.beat(BeatFraction.WHOLE))
    piano.note(midi.frequency_to_key(330), music.beat(BeatFraction.WHOLE))
    piano.note(midi.frequency_to_key(294), music.beat(BeatFraction.WHOLE))
    piano.note(midi.frequency_to_key(262), music.beat(BeatFraction.WHOLE))
    piano.note(midi.frequency_to_key(294), music.beat(BeatFraction.WHOLE))
    piano.note(midi.frequency_to_key(262), music.beat(BeatFraction.WHOLE))
    piano.note(midi.frequency_to_key(0), music.beat(BeatFraction.WHOLE))
    piano.note(midi.frequency_to_key(262), music.beat(BeatFraction.WHOLE))
    piano.note(midi.frequency_to_key(349), music.beat(BeatFraction.DOUBLE))
    piano.note(midi.frequency_to_key(349), music.beat(BeatFraction.WHOLE))
    piano.note(midi.frequency_to_key(349), music.beat(BeatFraction.WHOLE))
    piano.note(midi.frequency_to_key(392), music.beat(BeatFraction.WHOLE))
    piano.note(midi.frequency_to_key(440), music.beat(BeatFraction.WHOLE))
    piano.note(midi.frequency_to_key(392), music.beat(BeatFraction.DOUBLE))
input.on_button_pressed(Button.A, on_button_pressed_a)

piano: midi.MidiController = None
serial.redirect(SerialPin.P14, SerialPin.P0, BaudRate.BAUD_RATE31250)
midi.use_raw_serial()
piano = midi.channel(1)
piano.set_instrument(MidiInstrument.ACOUSTIC_GRAND_PIANO)
piano.control_change(7, 32)